services:
  ipca-realtime:
    container_name: ipca-realtime
    build: .
    ports:
      - ${RT_SERVER_EXPOSE_PORT}:${RT_SERVER_PORT}
    restart: on-failure
    volumes:
      - ./:/app/
    env_file:
      - .env
    networks:
      - ipca-stack
networks:
  ipca-stack:
    external: true
