services:
  ipca-realtime:
    container_name: ipca-realtime
    build: .
    ports:
      - ${SERVER_EXPOSE_PORT}:${SERVER_PORT}
    restart: on-failure
    env_file:
      - .env
    networks:
      - ipca-stack
networks:
  ipca-stack:
    external: true
